//로그인
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const GET_NOTICE_REQUEST = "GET_NOTICE_REQUEST";
export const GET_NOTICE_SUCCESS = "GET_NOTICE_SUCCESS";
export const GET_NOTICE_FAILURE = "GET_NOTICE_FAILURE";

export const POST_NOTICE_REQUEST = "POST_NOTICE_REQUEST"
export const POST_NOTICE_SUCCESS = "POST_NOTICE_SUCCESS";
export const POST_NOTICE_FAILURE = "POST_NOTICE_FAILURE";

export const MODAL_ISVISIBLE = "MODAL_ISVISIBLE";
